class tuple_exists_error(Exception):
    pass

class out_of_bounds_error(Exception):
    pass

