class tuple_exists_error(Exception):
    pass